"""agent protocol v2

Replaces the narrow Phase 2 agent_command_type/agent_command_status enums
with the full structured command set from docs/agent-protocol.md, adds the
agent_command_events audit trail, command metadata (correlation_id,
expires_at, result, error), enrollment token revocation, and agent
credential/capabilities columns.

agent_commands has no real rows in any environment this migration will ever
run against (Phase 4 is the first phase that writes to it), so the enum
member sets are replaced outright via rename/recreate/drop rather than
reconciled value-by-value — TRUNCATE is a safety net, not a data loss risk
here.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-22 09:26:25.532549

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

NEW_COMMAND_TYPES = (
    "INSPECT_HOST",
    "VALIDATE_APP",
    "DEPLOY_RELEASE",
    "START_INSTANCE",
    "STOP_INSTANCE",
    "RESTART_INSTANCE",
    "INSPECT_INSTANCE",
    "COLLECT_LOGS",
    "COLLECT_METRICS",
    "UPDATE_PROXY",
)
OLD_COMMAND_TYPES = ("DEPLOY", "INSTANCE_START", "INSTANCE_STOP", "INSTANCE_RESTART")

NEW_COMMAND_STATUSES = (
    "PENDING",
    "SENT",
    "ACKNOWLEDGED",
    "RUNNING",
    "SUCCEEDED",
    "FAILED",
    "TIMED_OUT",
    "EXPIRED",
)
OLD_COMMAND_STATUSES = ("PENDING", "SENT", "ACKED", "FAILED", "EXPIRED")


def _replace_enum(type_name: str, column: str, new_values: tuple[str, ...]) -> None:
    old_type_name = f"{type_name}_prev"
    values_sql = ", ".join(f"'{v}'" for v in new_values)
    op.execute(f"ALTER TYPE {type_name} RENAME TO {old_type_name}")
    op.execute(f"CREATE TYPE {type_name} AS ENUM ({values_sql})")
    op.execute(
        f"ALTER TABLE agent_commands ALTER COLUMN {column} TYPE {type_name} "
        f"USING {column}::text::{type_name}"
    )
    op.execute(f"DROP TYPE {old_type_name}")


def upgrade() -> None:
    op.execute("TRUNCATE TABLE agent_commands CASCADE")
    _replace_enum("agent_command_type", "command_type", NEW_COMMAND_TYPES)
    _replace_enum("agent_command_status", "status", NEW_COMMAND_STATUSES)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_command_events",
        sa.Column("command_id", sa.UUID(), nullable=False),
        # create_type=False: the type was already created above by _replace_enum;
        # letting SQLAlchemy try to (re)create it here races with that and fails
        # with "type already exists".
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "SENT",
                "ACKNOWLEDGED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "TIMED_OUT",
                "EXPIRED",
                name="agent_command_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["command_id"], ["agent_commands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_command_events_command_id_occurred_at",
        "agent_command_events",
        ["command_id", "occurred_at"],
        unique=False,
    )
    op.add_column("agent_commands", sa.Column("correlation_id", sa.UUID(), nullable=True))
    op.add_column(
        "agent_commands", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "agent_commands",
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("agent_commands", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("agents", sa.Column("credential_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "agents", sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.create_unique_constraint("uq_agents_credential_hash", "agents", ["credential_hash"])
    op.add_column(
        "enrollment_tokens", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enrollment_tokens", "revoked_at")
    op.drop_constraint("uq_agents_credential_hash", "agents", type_="unique")
    op.drop_column("agents", "capabilities")
    op.drop_column("agents", "credential_hash")
    op.drop_column("agent_commands", "error")
    op.drop_column("agent_commands", "result")
    op.drop_column("agent_commands", "expires_at")
    op.drop_column("agent_commands", "correlation_id")
    op.drop_index(
        "ix_agent_command_events_command_id_occurred_at", table_name="agent_command_events"
    )
    op.drop_table("agent_command_events")
    # ### end Alembic commands ###

    op.execute("TRUNCATE TABLE agent_commands CASCADE")
    _replace_enum("agent_command_status", "status", OLD_COMMAND_STATUSES)
    _replace_enum("agent_command_type", "command_type", OLD_COMMAND_TYPES)
